name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ] # 当推送到 main 或 master 分支时触发

# 设置权限，允许 GitHub Actions 部署到 Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # Vite 默认的打包输出目录

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
